### PR TITLE
Added PHP 8.2 compatibility for laminas/laminas-code

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### Description

- Update composer config platform php to 8.0.99
- Update composer PHP to ~7.4.0 || ~8.0.0 || ~8.1.0 || ~8.2.0
- Added and Ignore PHP platform requirements via .laminas-ci.json

### CODE REVIEW

**Comment by Ocramius** [comment]
@glo71317 BTW, what is up with your internal company ticket number added to a public repo commit? 😛

**Comment by glo71317** [comment]
> @glo71317 BTW, what is up with your internal company ticket number added to a public repo commit? 😛

@Ocramius I have updated the title of the ticket and some tests are getting failed any suggestion on this anything require at our end.

**Comment by Ocramius** [comment]
For laminas-code specifically, there's an entire milestone of stuff to be done, which I haven't done yet 😬

**Comment by glo71317** [comment]
@Ocramius Anything needed from our end for this

**Comment by Ocramius** [comment]
Nope, just lots of housekeeping on this end.

**Comment by glo71317** [comment]
This PR is not required because php 8.2 support is added under this PR - https://github.com/laminas/laminas-code/pull/147

**Pull request closed without merging**
