### PR TITLE
Added Php8.2 support

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by glo71317** [comment]
@Ocramius Can you review our PR and proceed for merging if there is no pr comments and PR is green now

**Comment by Ocramius** [comment]
This is a duplicate of current `4.8.0` milestone efforts. You already opened #151 some days ago.

I know you folks are sharing github accounts over there, so perhaps talk to each other? :-) 

Closing here: the rest of the work to be done is still in https://github.com/laminas/laminas-code/milestone/30

**Comment by glo71317** [comment]
> This is a duplicate of current `4.8.0` milestone efforts. You already opened #151 some days ago.
> 
> I know you folks are sharing github accounts over there, so perhaps talk to each other? :-)
> 
> Closing here: the rest of the work to be done is still in https://github.com/laminas/laminas-code/milestone/30

@Ocramius So when we can expect php8.2 support will be available for community.

**Comment by Ocramius** [comment]
Whenever I get time to work on the queued issues.

**Pull request closed without merging**
