### PR TITLE
Add php 8 support to 3.4

### PR DESCRIPTION
**Pull request by 4c0n**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This PR adds PHP 8 support to the 3.4 version.

### CODE REVIEW

**Comment by Ocramius** [comment]
Duplicate of #110 - `3.4.x` is for bugfix-only: please upgrade.

**Comment by 4c0n** [comment]
@Ocramius So this is a sub dependency, so I cannot just upgrade to a new major version. Guess I'll have to lobby at the other project then, however there is little to no chance that they will respond... So then I'm stuck with a fork for this tiny change...

**Comment by 4c0n** [comment]
https://github.com/Sylius/Sylius/blob/49b070933b32761de08475fafd6d86dca10d40ff/composer.json#L164

**Comment by Ocramius** [comment]
@4c0n if sylius has issues with `laminas/laminas-code:^4`, that really needs resolution here: the problem shouldn't be propagated to other dependencies.

The source of the problem seems to be https://github.com/Sylius/Sylius/commit/f80f42d06ffb98a8a5ffaaf543ccd646cdd202c6, and I suggest talking to @pamil directly: they are quite responsive :-) 

It's most likely fixable there, but asking other projects to increase dependency ranges is not viable, especially if not accompanied with extensive testing of those dependencies, which I've done @ https://github.com/laminas/laminas-code/compare/3.5.1...4.0.0 (should give you an idea of the extent of work put in it).

The code in `3.x` does **not** run against PHP 8 reflected symbols: it will just crash in bizarre ways, so it will "install", but ((it won't really be compatible** with 8.0+.

**Comment by 4c0n** [comment]
@Ocramius Thanks for your elaboration, it helps clear a lot up. Unfortunately Kamil is no longer a part of the Sylius team and lately they have not been very responsive at all. I don't know why exactly, but using my fork on PHP8 is not crashing at all, maybe it's just a dependency that is going unused then.
I guess I'll keep it for now and hopefully someone at the Sylius team will have a look at it and respond.

Thanks again!

**Comment by Ocramius** [comment]
Keeping a fork while the issue is being fixed upstream is certainly a workaround.

You can also try a `"require": {"laminas/laminas-code": "4.4.3 as 3.99.99"}` to trick `composer` into thinking it's compatible.

**Pull request closed without merging**
